import { createHash } from 'node:crypto'
import { mkdir, readFile, rename, writeFile, copyFile } from 'node:fs/promises'
import path from 'node:path'
import { DspAdapter } from './DspAdapter.js'
import { validateDspConfiguration } from '../../validation/dspConfig.js'

function hash(value) { return createHash('sha256').update(value).digest('hex') }
export function serializeEqualizerApo(configuration) {
  const validation = validateDspConfiguration(configuration); if (!validation.ok) throw new TypeError(validation.errors.join('; '))
  const lines = ['# Generated by Sonos Controller EQ sandbox', `Preamp: ${configuration.enabled === false ? 0 : configuration.preampDb} dB`]
  for (const band of configuration.graphicEq?.bands ?? []) if (band.enabled) lines.push(`Filter: ON PK Fc ${band.frequencyHz} Hz Gain ${band.gainDb} dB Q 4.318`)
  for (const filter of configuration.parametricEq?.filters ?? []) if (filter.enabled) lines.push(`Filter: ON ${filter.type === 'peak' ? 'PK' : filter.type} Fc ${filter.frequencyHz} Hz Gain ${filter.gainDb} dB Q ${filter.q}`)
  return `${lines.join('\n')}\n`
}
export class EqualizerApoAdapter extends DspAdapter {
  constructor({ sandboxRoot, liveEnabled = false } = {}) { super(); if (!sandboxRoot) throw new TypeError('sandboxRoot is required'); this.root = path.resolve(sandboxRoot); this.liveEnabled = liveEnabled; this.history = []; this.bypassed = false }
  async probe() { return { engine: 'equalizer-apo', mode: 'sandbox_only', available: true, liveAudioProcessed: false, root: this.root } }
  validateConfiguration(config) { return validateDspConfiguration(config) }
  async getStatus() { return { engine: 'equalizer-apo', mode: 'sandbox_only', bypassed: this.bypassed, activeVersionId: this.history.at(-1)?.versionId ?? null, liveAudioProcessed: false } }
  async getConfiguration() { try { return { text: await readFile(path.join(this.root, 'active.txt'), 'utf8') } } catch { return null } }
  async applyConfiguration(config) { const text = serializeEqualizerApo(config); await mkdir(this.root, { recursive: true }); const active = path.join(this.root, 'active.txt'); const staged = path.join(this.root, `staged-${Date.now()}.txt`); const backup = path.join(this.root, 'active.previous.txt'); try { await readFile(active); await copyFile(active, backup) } catch (cause) { if (cause.code !== 'ENOENT') throw cause }; await writeFile(staged, text, { flag: 'wx' }); await rename(staged, active); const versionId = hash(text); this.history.push({ versionId, backup }); return { ok: true, status: 'sandbox_applied', versionId, hash: versionId, liveAudioProcessed: false } }
  async bypass(enabled) { this.bypassed = Boolean(enabled); return { ok: true, status: 'sandbox_bypass', bypassed: this.bypassed, liveAudioProcessed: false } }
  async rollback() { const active = path.join(this.root, 'active.txt'); const backup = path.join(this.root, 'active.previous.txt'); await copyFile(backup, active); return { ok: true, status: 'sandbox_rolled_back', liveAudioProcessed: false } }
}
