import { createHash } from 'node:crypto'
import { lstat, mkdir, readFile, rename, writeFile, copyFile } from 'node:fs/promises'
import path from 'node:path'
import { DspAdapter } from './DspAdapter.js'
import { validateDspConfiguration } from '../../validation/dspConfig.js'

function hash(value) { return createHash('sha256').update(value).digest('hex') }
export function serializeEqualizerApo(configuration) {
  const validation = validateDspConfiguration(configuration); if (!validation.ok) throw new TypeError(validation.errors.join('; '))
  const lines = ['# Generated by Sonos Controller EQ sandbox', `Preamp: ${configuration.enabled === false ? 0 : configuration.preampDb} dB`]
  for (const band of configuration.graphicEq?.bands ?? []) if (band.enabled) lines.push(`Filter: ON PK Fc ${band.frequencyHz} Hz Gain ${band.gainDb} dB Q 4.318`)
  for (const filter of configuration.parametricEq?.filters ?? []) if (filter.enabled) lines.push(`Filter: ON ${filter.type === 'peak' ? 'PK' : filter.type} Fc ${filter.frequencyHz} Hz Gain ${filter.gainDb} dB Q ${filter.q}`)
  return `${lines.join('\n')}\n`
}
export class EqualizerApoAdapter extends DspAdapter {
  constructor({ sandboxRoot, readinessPath = null, liveEnabled = false } = {}) { super(); if (!sandboxRoot) throw new TypeError('sandboxRoot is required'); if (liveEnabled) throw new TypeError('live Equalizer APO mode is not supported'); if (readinessPath !== null && (typeof readinessPath !== 'string' || !path.isAbsolute(readinessPath))) throw new TypeError('readinessPath must be an absolute explicit path'); this.root = path.resolve(sandboxRoot); this.readinessPath = readinessPath; this.history = []; this.bypassed = false; this.stagedConfiguration = null }
  async probe() { let readiness = { status: 'not_configured' }; if (this.readinessPath) { try { const candidate = await lstat(this.readinessPath); readiness = { status: candidate.isFile() ? 'candidate_present' : 'candidate_not_file', path: this.readinessPath } } catch (cause) { readiness = { status: cause.code === 'ENOENT' ? 'candidate_missing' : 'candidate_unavailable', path: this.readinessPath } } } return { engine: 'equalizer-apo', mode: 'sandbox_only', available: true, readiness, liveAudioProcessed: false, root: this.root } }
  validateConfiguration(config) { return validateDspConfiguration(config) }
  async getStatus() { return { engine: 'equalizer-apo', mode: 'sandbox_only', bypassed: this.bypassed, activeVersionId: this.history.at(-1)?.versionId ?? null, hasStagedConfiguration: this.stagedConfiguration !== null, liveAudioProcessed: false } }
  async ensureSandbox() { await mkdir(this.root, { recursive: true }); if ((await lstat(this.root)).isSymbolicLink()) throw new Error('SANDBOX_ROOT_SYMLINK_DENIED') }
  async safeFile(name) { await this.ensureSandbox(); const candidate = path.resolve(this.root, name); if (path.relative(this.root, candidate).startsWith('..') || path.isAbsolute(path.relative(this.root, candidate))) throw new Error('SANDBOX_PATH_DENIED'); try { if ((await lstat(candidate)).isSymbolicLink()) throw new Error('SANDBOX_SYMLINK_DENIED') } catch (cause) { if (cause.code !== 'ENOENT') throw cause } return candidate }
  async getConfiguration() { try { return { text: await readFile(await this.safeFile('active.txt'), 'utf8') } } catch { return null } }
  async stageConfiguration(config) { const validation = this.validateConfiguration(config); if (!validation.ok) return { ok: false, staged: false, errors: validation.errors }; this.stagedConfiguration = structuredClone(config); return { ok: true, staged: true, applied: false, liveAudioProcessed: false } }
  async applyConfiguration(config) { const text = serializeEqualizerApo(config); const active = await this.safeFile('active.txt'); const staged = await this.safeFile(`staged-${Date.now()}.txt`); const backup = await this.safeFile('active.previous.txt'); try { await readFile(active); await copyFile(active, backup) } catch (cause) { if (cause.code !== 'ENOENT') throw cause }; await writeFile(staged, text, { flag: 'wx' }); await rename(staged, active); this.stagedConfiguration = null; const versionId = hash(text); this.history.push({ versionId, backup }); return { ok: true, status: 'sandbox_applied', versionId, hash: versionId, liveAudioProcessed: false } }
  async bypass(enabled) { this.bypassed = Boolean(enabled); return { ok: true, status: 'sandbox_bypass', bypassed: this.bypassed, liveAudioProcessed: false } }
  async rollback() { const active = await this.safeFile('active.txt'); const backup = await this.safeFile('active.previous.txt'); await copyFile(backup, active); return { ok: true, status: 'sandbox_rolled_back', liveAudioProcessed: false } }
}
